database_url: "{{ vault_database_url }}"
app_key: "{{ vault_app_key }}"
db_host: "{{ vault_db_host }}"
db_port: "{{ vault_db_port }}"
db_database: "{{ vault_db_database }}"
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"
